Repository didx-xyz/acapy-cloud, pull requests merged in 2023-08, with the labels that each got.

#411 Fix connection re-use in retry of issuer onboarding
  app/admin/tenants/onboarding.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_fixtures.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/tenants.py
  app/util/retry_method.py
  app/util/string.py
  trustregistry/tests/test_actor.py
Labels: bug

#412 :art: Refactoring continued
  app/dependencies/auth.py
  app/models/tenants.py
  app/routes/admin/tenants.py
  app/routes/issuer.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_issuer.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_messaging.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/test_verifier.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/tenants.py
  app/tests/util/trust_registry.py
  endorser/endorser_processor.py
Labels: improvement

#414 Add issuing of JSON-LD credentials
  app/models/issuer.py
  app/requirements.txt
  app/routes/issuer.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/onboarding.py
  app/services/trust_registry.py
  app/tests/e2e/test_issuer.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/util/retry_method.py
  endorser/requirements.txt
  webhooks/requirements.txt
Labels: enhancement

#420 Upgrade tails-server and von-network
  .github/workflows/continuous-deploy.yml
  docker-compose.yaml
Labels: enhancement

#424 Refactor verifier models, service and routes to support jsonld
  app/models/issuer.py
  app/models/tenants.py
  app/models/verifier.py
  app/routes/admin/tenants.py
  app/routes/verifier.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/test_verifier.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/verifier/test_verifier.py
  app/tests/verifier/utils.py
  app/util/acapy_verifier_utils.py
  app/util/tenants.py
  docs/Common Steps.md
Labels: enhancement

#423 Containerize tests
  .dockerignore
  .gitignore
  docker-compose.yaml
  dockerfiles/tests/Dockerfile
  manage
  requirements.dev.txt
  scripts/loop_tests.sh
  scripts/summary.py
Labels: enhancement
