Repository didx-xyz/acapy-cloud, pull requests merged in 2023-10, with the labels that each got.

#479 :bug: Fix ACA-Py race condition in configuration of endorser connection
  app/services/onboarding.py
  app/tests/admin/test_onboarding.py
  app/util/assert_connection_metadata.py
Labels: bug

#484 :sparkles: Add credentials routes to wallet module
  app/main.py
  app/routes/wallet/__init__.py
  app/routes/wallet/credentials.py
  app/routes/wallet/dids.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed25519.py
  app/tests/e2e/issuer/did_sov/test_v2_ld.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/test_wallet_dids.py
  app/tests/util/trust_registry.py
Labels: enhancement

#492 🎨 refactor onboarding and 🐛 fix setting of endorser metadata
  .gitignore
  app/event_handling/sse_listener.py
  app/routes/admin/tenants.py
  app/services/onboarding.py
  app/services/onboarding/__init__.py
  app/services/onboarding/issuer.py
  app/services/onboarding/tenants.py
  app/services/onboarding/util/__init__.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/onboarding/util/set_endorser_metadata.py
  app/services/onboarding/verifier.py
  app/tests/admin/test_onboarding.py
  app/tests/e2e/issuer/did_key_bbs/test_ld_bbs.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed25519.py
  app/util/assert_connection_metadata.py
Labels: bug, enhancement

#500 Hotfix: Helm `3.13.1`
  .github/workflows/continuous-deploy.yml
Labels: bug

#505 :boom::sparkles: Use new cloudcontroller and upgrade pydantic to v2
  app/main.py
  app/models/definitions.py
  app/models/issuer.py
  app/models/jsonld.py
  app/models/oob.py
  app/models/tenants.py
  app/models/verifier.py
  app/requirements.txt
  app/routes/admin/tenants.py
  app/routes/definitions.py
  app/routes/jsonld.py
  app/routes/messaging.py
  app/routes/oob.py
  app/routes/wallet/credentials.py
  app/routes/wallet/dids.py
  app/services/acapy_ledger.py
  app/services/acapy_wallet.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/onboarding/issuer.py
  app/services/onboarding/tenants.py
  app/tests/admin/test_onboarding.py
  app/tests/e2e/conftest.py
  app/tests/e2e/issuer/did_key_bbs/test_ld_bbs.py
  app/tests/e2e/issuer/did_key_bbs/test_ld_bbs_x.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed25519.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed_x.py
  app/tests/e2e/issuer/did_sov/test_v2_ld.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_messaging.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/test_verifier.py
  app/tests/e2e/test_wallet_dids.py
  app/tests/services/test_acapy_ledger.py
  app/tests/services/test_acapy_wallet.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/test_auth.py
  app/tests/test_definitions.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/ledger.py
  app/tests/util/tenants.py
  app/tests/verifier/utils.py
  app/util/tenants.py
  endorser/endorser_processor.py
  endorser/requirements.txt
  endorser/tests/test_endorser_processor.py
  requirements.dev.txt
  shared/models/topics/base.py
  shared/models/trustregistry.py
  shared/util/rich_async_client.py
  shared/util/rich_parsing.py
  trustregistry/crud.py
  trustregistry/registry/registry_schemas.py
  trustregistry/requirements.txt
  trustregistry/tests/test_actor.py
  webhooks/dependencies/service.py
  webhooks/requirements.txt
Labels: enhancement

#512 :sparkles: add multitenancy-config for askar wallets
  environments/governance-ga/aca-py-agent.default.env
  environments/governance-multitenant/aca-py-agent.default.env
Labels: enhancement

#513 :arrow_up: upgrade wallet-plugin
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
Labels: enhancement

#515 :sparkles: Reuse SSL cert context for all HTTP requests
  app/event_handling/sse_listener.py
  app/services/sse.py
  app/services/trust_registry.py
  app/tests/conftest.py
  app/tests/e2e/test_exception_handler.py
  app/tests/services/test_trust_registry.py
  app/tests/util/ledger.py
  app/tests/util/webhooks.py
  endorser/endorser_processor.py
  endorser/tests/test_endorser_processor.py
  shared/util/rich_async_client.py
  trustregistry/tests/test_actor.py
  trustregistry/tests/test_main.py
  trustregistry/tests/test_schema.py
  webhooks/tests/test_sse.py
  webhooks/tests/test_webhooks.py
Labels: enhancement

#520 :art: rename tenant_id to wallet_id
  app/models/tenants.py
  app/routes/admin/tenants.py
  app/services/onboarding/tenants.py
  app/tests/e2e/issuer/did_sov/test_v1_indy.py
  app/tests/e2e/issuer/did_sov/test_v2_indy.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/test_verifier.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/member_wallets.py
  app/tests/util/tenants.py
  app/util/tenants.py
  docs/Governance as Code.md
Labels: refactor

#496 :art::sparkles: refactor trust-registry service and implement additional routes
  app/models/tenants.py
  app/models/trust_registry.py
  app/routes/admin/tenants.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/trust_registry.py
  app/routes/verifier.py
  app/routes/webhooks.py
  app/services/onboarding/tenants.py
  app/services/sse.py
  app/services/trust_registry.py
  app/services/trust_registry/__init__.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/services/trust_registry/util/__init__.py
  app/services/trust_registry/util/actor.py
  app/services/trust_registry/util/issuer.py
  app/services/trust_registry/util/schema.py
  app/services/webhooks.py
  app/tests/conftest.py
  app/tests/e2e/conftest.py
  app/tests/e2e/issuer/did_key_bbs/test_ld_bbs.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed25519.py
  app/tests/e2e/issuer/did_sov/test_v1_indy.py
  app/tests/e2e/issuer/did_sov/test_v2_indy.py
  app/tests/e2e/issuer/did_sov/test_v2_ld.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/test_wallet_dids.py
  app/tests/services/test_trust_registry.py
  app/tests/services/test_webhooks.py
  app/tests/util/client.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/ledger.py
  app/tests/util/member_async_clients.py
  app/tests/util/trust_registry.py
  app/tests/verifier/test_verifier.py
  app/tests/verifier/utils.py
  app/util/acapy_verifier_utils.py
  endorser/endorser_processor.py
  endorser/tests/test_endorser_processor.py
  shared/util/rich_async_client.py
  trustregistry/crud.py
  trustregistry/registry/registry_actors.py
  trustregistry/registry/registry_schemas.py
  trustregistry/tests/test_actor.py
  trustregistry/tests/test_schema.py
  webhooks/tests/test_sse.py
Labels: enhancement

#516 :sparkles: add wallet_name to create tenant request, and allow fetch by wallet_name
  app/models/tenants.py
  app/requirements.txt
  app/routes/admin/tenants.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/jsonld.py
  app/services/acapy_ledger.py
  app/services/onboarding/issuer.py
  app/services/onboarding/tenants.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/onboarding/util/set_endorser_metadata.py
  app/services/onboarding/verifier.py
  app/services/revocation_registry.py
  app/tests/admin/test_onboarding.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry.py
  app/tests/services/test_acapy_ledger.py
  app/tests/services/test_revocation_registry.py
  app/tests/util/tenants.py
  app/util/tenants.py
  docs/Governance as Code.md
  endorser/requirements.txt
  webhooks/requirements.txt
Labels: enhancement

#523 :wrench: Don't ignore test failures in the ignore-teardown-errors workaround
  .github/workflows/continuous-deploy.yml
  app/tests/e2e/test_definitions.py
Labels: bug
