Repository didx-xyz/acapy-cloud, pull requests merged in 2023-07, with the labels that each got.

#372 Get schema by id
  app/event_handling/listener.py
  app/facades/trust_registry.py
  app/generic/connections/connections.py
  app/generic/issuer/facades/acapy_issuer.py
  app/generic/issuer/facades/acapy_issuer_v1.py
  app/generic/issuer/facades/acapy_issuer_v2.py
  app/generic/issuer/issuer.py
  app/generic/oob/oob.py
  app/generic/verifier/facades/acapy_verifier.py
  app/generic/verifier/facades/acapy_verifier_v1.py
  app/generic/verifier/facades/acapy_verifier_v2.py
  app/generic/verifier/verifier.py
  app/generic/webhooks.py
  app/tests/e2e/test_fixtures.py
  app/tests/e2e/test_issuer.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_verifier.py
  app/tests/e2e/test_webhook.py
  app/tests/facades/test_trust_registry.py
  app/tests/facades/test_webhooks.py
  app/tests/issuer/test_issuer.py
  app/tests/verifier/test_acapy_verifier_v1_facade.py
  app/tests/verifier/test_acapy_verifier_v2_facade.py
  app/tests/verifier/test_verifier.py
  app/tests/verifier/utils.py
  endorser/endorser_processor.py
  endorser/tests/test_endorser_processor.py
  shared/models/__init__.py
  shared/models/conversion.py
  shared/models/topics/__init__.py
  shared/models/trustregistry.py
  trustregistry/crud.py
  trustregistry/db.py
  trustregistry/main.py
  trustregistry/models.py
  trustregistry/registry/registry_actors.py
  trustregistry/registry/registry_schemas.py
  trustregistry/tests/test_models.py
  trustregistry/tests/test_schema.py
  trustregistry/tests/test_schemas.py
  webhooks/dependencies/event_generator_wrapper.py
  webhooks/dependencies/service.py
  webhooks/dependencies/sse_manager.py
  webhooks/models.py
  webhooks/routers/receive_events.py
  webhooks/routers/webhooks.py
Labels: enhancement

#378 Update `manage` script to use Docker Compose V2
  .github/workflows/continuous-build.yml
  manage
Labels: dependencies

#377 Feat/create actor checks
  trustregistry/crud.py
  trustregistry/registry/registry_actors.py
  trustregistry/tests/test_actor.py
Labels: improvement

#360 SSE Manager: handle potential KeyErrors in cleanup process
  webhooks/dependencies/sse_manager.py
  webhooks/routers/sse.py
Labels: bug

#381 ed25519 verkey validation in did conversion
  app/tests/test_did.py
  app/util/did.py
Labels: enhancement

#384 Trustregistry migrate to postgres
  app/requirements.txt
  docker-compose.yaml
  endorser/requirements.dev.txt
  endorser/requirements.txt
  environments/trustregistry/trustregistry.default.env
  requirements.txt
  trustregistry/crud.py
  trustregistry/database.py
  trustregistry/main.py
  trustregistry/requirements.txt
  webhooks/requirements.txt
Labels: improvement

#389 Upgrade ACA-Py agents to 0.8.1
  app/admin/tenants/onboarding.py
  app/requirements.txt
  app/tests/e2e/test_verifier.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/requirements.txt
  webhooks/requirements.txt
Labels: dependencies

#390 Test get actor
  trustregistry/tests/test_actor.py
Labels: enhancement

#395 Upgrade ACA-Py agents to 0.8.2
  app/main.py
  app/requirements.txt
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/requirements.txt
  trustregistry/main.py
  webhooks/main.py
  webhooks/requirements.txt
Labels: dependencies

#396 Fix accept proof OOB tests and fix delete wallet requests
  app/admin/tenants/tenants.py
  app/tests/e2e/test_verifier.py
Labels: enhancement

#401 Feat/retry logic for endorser connection
  app/admin/tenants/onboarding.py
  app/util/retry_method.py
Labels: enhancement

#400 Upgrade ACA-Py agents to 0.9.0
  app/admin/tenants/onboarding.py
  app/main.py
  app/requirements.txt
  app/util/retry_method.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/webhooks/Dockerfile
  endorser/requirements.txt
  trustregistry/main.py
  webhooks/main.py
  webhooks/requirements.txt
Labels: dependencies

#399 Pre commit hook black
  .github/workflows/blackformat.yml
  .pre-commit-config.yaml
  requirements.dev.txt
Labels: enhancement

#405 Add isort to code style workflow and organise imports
  .github/workflows/blackformat.yml
  .github/workflows/style-check.yml
  .isort.cfg
  app/admin/tenants/models.py
  app/exceptions/cloud_api_error.py
  app/tests/e2e/test_tenants.py
  app/tests/test_definitions.py
  endorser/tests/test_endorser_processor.py
  requirements.dev.txt
  shared/models/conversion.py
  trustregistry/registry/registry_schemas.py
  webhooks/clients.example.py
Labels: enhancement

#402 Redis event revocation
  app/main.py
  shared/models/topics/__init__.py
  webhooks/dependencies/service.py
Labels: topic: webhooks

#409 Add retry logic for onboarding an issuer with no public DID
  app/admin/tenants/onboarding.py
  app/util/retry_method.py
Labels: bug, enhancement
