Repository didx-xyz/acapy-cloud, pull requests merged in 2023-12, with the labels that each got.

#552 :sparkles: Add `save_exchange_record` argument to send credentials
  app/models/issuer.py
  app/services/issuer/acapy_issuer.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/tests/e2e/test_credentials.py
Labels: enhancement

#525 :white_check_mark: Fix creating connections with `use_public_did`
  app/models/connections.py
  app/routes/connections.py
  app/services/verifier/acapy_verifier_v1.py
  app/tests/e2e/test_connections.py
  docker-compose.yaml
  environments/governance-ga/aca-py-agent.default.env
  environments/governance-multitenant/aca-py-agent.default.env
Labels: enhancement

#574 :white_check_mark: Fix some spurious test failures
  app/dependencies/auth.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_webhooks.py
Labels: bug

#539 :zap: Set issuer fixture scope to session level
  .github/workflows/continuous-deploy.yml
  app/tests/e2e/test_credentials.py
  app/tests/util/member_acapy_clients.py
  app/tests/util/member_async_clients.py
  app/tests/util/member_wallets.py
  shared/util/mock_agent_controller.py
Labels: enhancement

#571 :sparkles: make websocket event publishing stateless
  webhooks/dependencies/sse_manager.py
  webhooks/dependencies/websocket.py
  webhooks/main.py
  webhooks/routers/receive_events.py
  webhooks/tests/test_receive_events.py
  webhooks/tests/test_sse_manager.py
Labels: enhancement

#579 :white_check_mark: fix teardown errors
  app/tests/e2e/test_credentials.py
  app/tests/util/member_acapy_clients.py
  app/tests/util/member_async_clients.py
  app/tests/util/member_wallets.py
Labels: bug

#586 :art: Update main and add test
  app/main.py
  app/tests/test_main.py
  trustregistry/main.py
  trustregistry/tests/test_main.py
  webhooks/dependencies/sse_manager.py
  webhooks/main.py
  webhooks/routers/websocket.py
  webhooks/tests/test_main.py
  webhooks/tests/test_sse_manager.py
Labels: enhancement

#572 :sparkles: add env config to disable file logging or colorizing
  shared/log_config.py
Labels: enhancement

#587 :sparkles: Add `lookback_time` query parameter to SSE routes
  app/event_handling/sse_listener.py
  app/models/issuer.py
  app/models/verifier.py
  app/tests/e2e/test_tenants.py
  webhooks/dependencies/sse_manager.py
  webhooks/routers/sse.py
Labels: enhancement

#546 Update docs
  README.md
  docs/Admin.md
  docs/Bootstrap Trust Ecosystem.md
  docs/Common Steps.md
  docs/Example Flows.md
  docs/Governance as Code.md
  docs/Introduction.md
  docs/Multitenant.md
  docs/Quick Start Guide.md
  docs/README.md
  docs/Trust Registry.md
  docs/Webhooks.md
  docs/Workflows Overview.md
  docs/examples/1. Onboarding.md
  docs/examples/2. Create Schema.md
  docs/examples/3. Create Credential Definition.md
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/5. Issue Credential.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
Labels: documentation

#607 Patch concurrency group
  .github/workflows/continuous-deploy.yml
Labels: bug

#608 Don't deploy if PR Draft or Dependabot
  .github/workflows/continuous-deploy.yml
Labels: github_actions

#613 `triggering_actor` -> `actor`
  .github/workflows/continuous-deploy.yml
Labels: bug
