Repository didx-xyz/acapy-cloud, pull requests merged in 2023-11, with the labels that each got.

#532 :sparkles::art: Refactor webhooks and make SseManager stateless
  app/event_handling/sse_listener.py
  app/routes/connections.py
  app/routes/issuer.py
  app/routes/oob.py
  app/routes/verifier.py
  app/routes/webhooks.py
  app/services/issuer/acapy_issuer.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/services/webhooks.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_verifier.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/test_webhook.py
  app/tests/issuer/test_issuer.py
  app/tests/services/test_webhooks.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/webhooks.py
  app/tests/verifier/test_verifier.py
  app/tests/verifier/utils.py
  endorser/endorser_processor.py
  shared/models/conversion.py
  shared/models/webhook_topics/__init__.py
  shared/models/webhook_topics/base.py
  shared/util/rich_parsing.py
  webhooks/dependencies/container.py
  webhooks/dependencies/event_generator_wrapper.py
  webhooks/dependencies/redis.py
  webhooks/dependencies/redis_service.py
  webhooks/dependencies/service.py
  webhooks/dependencies/sse_manager.py
  webhooks/models.py
  webhooks/routers/receive_events.py
  webhooks/routers/sse.py
  webhooks/routers/webhooks.py
  webhooks/tests/conftest.py
  webhooks/tests/e2e/__init__.py
  webhooks/tests/e2e/conftest.py
  webhooks/tests/e2e/test_sse.py
  webhooks/tests/e2e/test_webhooks.py
  webhooks/tests/test_receive_events.py
  webhooks/tests/test_redis_service.py
  webhooks/tests/test_sse_manager.py
Labels: enhancement

#540 Update tenant-admin auth
  app/dependencies/auth.py
  app/dependencies/role.py
  app/routes/admin/tenants.py
Labels: bug, enhancement

#533 Add per wallet config settings
  app/models/tenants.py
  app/routes/admin/tenants.py
  app/services/onboarding/tenants.py
  app/tests/e2e/test_tenants.py
Labels: enhancement

#517 :bug::white_check_mark: Fix asserting valid verifier when actor has both issuer and verifier roles
  app/routes/verifier.py
  app/services/onboarding/issuer.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/onboarding/util/set_endorser_metadata.py
  app/services/verifier/acapy_verifier_v1.py
  app/tests/conftest.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_verifier.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/member_acapy_clients.py
  app/tests/util/member_async_clients.py
  app/tests/util/member_wallets.py
  app/tests/util/tenants.py
  app/util/acapy_verifier_utils.py
  environments/webhooks/fastapi.webhooks.env
  webhooks/main.py
  webhooks/routers/receive_events.py
  webhooks/tests/test_receive_events.py
  webhooks/tests/test_sse_manager.py
Labels: bug, enhancement

#541 :arrow_up: Upgrade to latest cloudcontroller
  app/requirements.txt
  app/tests/test_auth.py
  endorser/requirements.txt
  trustregistry/requirements.txt
  webhooks/requirements.txt
Labels: enhancement, dependencies

#545 :bug::white_check_mark: Fix assert valid verifier when using invite not from trust registry
  app/exceptions/__init__.py
  app/exceptions/cloudapi_exception.py
  app/main.py
  app/routes/admin/tenants.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/jsonld.py
  app/routes/verifier.py
  app/routes/wallet/dids.py
  app/services/acapy_ledger.py
  app/services/acapy_wallet.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/onboarding/issuer.py
  app/services/onboarding/tenants.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/onboarding/util/set_endorser_metadata.py
  app/services/onboarding/verifier.py
  app/services/revocation_registry.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/services/trust_registry/util/actor.py
  app/services/trust_registry/util/issuer.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/admin/test_onboarding.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_verifier.py
  app/tests/services/test_acapy_ledger.py
  app/tests/services/test_acapy_wallet.py
  app/tests/services/test_revocation_registry.py
  app/tests/services/test_trust_registry.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/webhooks.py
  app/tests/verifier/utils.py
  app/util/acapy_issuer_utils.py
  app/util/acapy_verifier_utils.py
  app/util/tenants.py
Labels: bug, enhancement

#544 Disallow special characters in `wallet_label` and `wallet_name`, and limit max length
  app/models/tenants.py
  app/routes/admin/tenants.py
  app/tests/e2e/test_tenants.py
  shared/models/trustregistry.py
Labels: enhancement

#549 :sparkles: add env config for trust registry postgres engine
  trustregistry/database.py
Labels: enhancement

#548 :arrow_up::boom: Upgrade ACA-Py to 0.10.5
  app/main.py
  app/models/definitions.py
  app/requirements.txt
  app/routes/definitions.py
  app/routes/jsonld.py
  app/services/acapy_ledger.py
  app/services/revocation_registry.py
  app/services/verifier/acapy_verifier_v1.py
  app/tests/e2e/issuer/did_sov/test_v1_indy.py
  app/tests/e2e/issuer/did_sov/test_v2_indy.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_trust_registry_integration.py
  app/util/acapy_verifier_utils.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/requirements.txt
  trustregistry/main.py
  webhooks/main.py
  webhooks/requirements.txt
Labels: dependencies

#565 :white_check_mark: cleanup tenant after creation in test
  app/tests/e2e/test_tenants.py
Labels: bug

#568 :hammer: Update script for drop db
  scripts/aurora-delete.sh
Labels: bug
