Repository didx-xyz/acapy-cloud, pull requests merged in 2024-12, with the labels that each got.

#1216 ♻️Refactor revocation endpoints
  app/main.py
  app/routes/issuer.py
  app/routes/revocation.py
  app/tests/e2e/test_revocation.py
  app/tests/fixtures/credentials.py
  app/tests/routes/revocation/test_clear_pending_revocations.py
  app/tests/routes/revocation/test_get_credential_revocation_record.py
  app/tests/routes/revocation/test_get_pending_revocations.py
  app/tests/routes/revocation/test_publish_revocations.py
  app/tests/routes/revocation/test_revoke_credential.py
  app/tests/services/issuer/test_issuer.py
Labels: enhancement

#1206 ✨ Add endpoint to fix revocation registry state
  app/routes/revocation.py
  app/tests/e2e/test_revocation.py
  app/tests/routes/revocation/test_fix_revocation_registry.py
  app/tests/services/issuer/test_issuer.py
Labels: enhancement

#1218 ⬆️ Mise `2024.12.0`
  .github/workflows/continuous-deploy.yml
  .mise.toml
Labels: dependencies

#1205 ✅ Update test fixtures to did-exchange protocol
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/fixtures/member_connections.py
  app/tests/util/connections.py
Labels: tests

#1162 :arrow_up: :sparkles: Upgrade ACA-Py and resolve noisy error logs
  app/models/wallet.py
  app/poetry.lock
  app/pyproject.toml
  app/tests/e2e/test_did_rotate.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: testing

#987 :wrench: increase publish-revocations timeout and make configurable
  app/routes/revocation.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
Labels: bug, improvement

#1219 :bug: Fix registering issuer did
  app/pyproject.toml
  app/routes/revocation.py
  app/services/definitions/credential_definitions.py
  app/services/onboarding/issuer.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/onboarding/util/set_endorser_metadata.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/services/onboarding/test_onboarding.py
  app/tests/services/onboarding/test_register_issuer_did.py
  app/tests/util/connections.py
  app/tests/util/webhooks.py
  app/util/transaction_acked.py
  endorser/pyproject.toml
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  endorser/tests/test_main.py
  endorser/tests/test_util_endorsement.py
  endorser/util/endorsement.py
  pyproject.toml
  shared/constants.py
  trustregistry/pyproject.toml
  waypoint/pyproject.toml
  waypoint/services/nats_service.py
  waypoint/tests/services/test_nats_service.py
Labels: bug, improvement

#1228 ⬆️ Upgrade deprecated SonarCloud action
  .github/workflows/sonarcloud.yml
  pyproject.toml
Labels: dependencies

#1229 ⚡️ Endorser resubscribe
  endorser/poetry.lock
  endorser/pyproject.toml
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  waypoint/tests/services/test_nats_service.py
Labels: improvement

#1230 :memo: Update README
  README.md
Labels: documentation

#1249 :arrow_up: Upgrade uvicorn, protobuf, and update lock files
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies
