Repository didx-xyz/acapy-cloud, pull requests merged in 2024-08, with the labels that each got.

#953 :wrench: Increase default pagination `limit` to 1000 and :white_check_mark: fix regression tests when fetching many records
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/verifier/test_verifier.py
  app/util/pagination.py
Labels: improvement, tests

#950 :arrow_up: Bulk dependency upgrades: `black`, `fastapi`, `uvicorn`, `aiohttp`
  .github/workflows/style-check.yml
  .pre-commit-config.yaml
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#951 :art: fix lint warnings
  app/services/issuer/acapy_issuer.py
  app/tests/e2e/test_tenants.py
  dockerfiles/agents/Dockerfile
  scripts/k6/README.md
  webhooks/tests/e2e/test_sse.py
Labels: improvement

#956 :arrow_up: Upgrade redis and redis_events plugin dependencies
  app/poetry.lock
  docker-compose.yaml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#922 ✅ Add `self_attested_attributes` e2e test
  app/tests/e2e/verifier/test_self_attested.py
Labels: tests

#961 :adhesive_bandage: Remove `_backfill_events` method from webhooks service startup
  shared/services/redis_service.py
  webhooks/services/sse_manager.py
  webhooks/tests/services/test_sse_manager.py
Labels: improvement

#963 🩹 Increase expiry time of redis webhook event locks
  shared/services/redis_service.py
  webhooks/services/acapy_events_processor.py
  webhooks/tests/services/test_acapy_events_processor.py
Labels: bug, improvement

#973 :arrow_up: Upgrade dependencies: `aiohttp`, `orjson`, `pyjwt`, `pyyaml`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#980 :art: Ensure appropriate log levels for a production context
  app/main.py
  app/routes/admin/tenants.py
  app/routes/connections.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/jsonld.py
  app/routes/messaging.py
  app/routes/oob.py
  app/routes/sse.py
  app/routes/trust_registry.py
  app/routes/verifier.py
  app/routes/wallet/credentials.py
  app/routes/wallet/dids.py
  app/routes/wallet/jws.py
  app/routes/wallet/sd_jws.py
  app/routes/webhooks.py
  app/routes/websocket_endpoint.py
  app/services/acapy_ledger.py
  app/services/acapy_wallet.py
  app/services/definitions/schema_publisher.py
  app/services/definitions/schemas.py
  app/services/event_handling/websocket_manager.py
  app/services/onboarding/issuer.py
  app/services/onboarding/tenants.py
  app/services/onboarding/verifier.py
  app/services/revocation_registry.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/services/trust_registry/util/actor.py
  app/services/trust_registry/util/issuer.py
  app/services/trust_registry/util/schema.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/services/webhooks.py
  app/tests/util/ledger.py
  trustregistry/crud.py
  trustregistry/main.py
  trustregistry/registry/registry_actors.py
  trustregistry/registry/registry_schemas.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/billing_manager.py
  webhooks/services/webhooks_redis_service.py
  webhooks/web/routers/sse.py
  webhooks/web/routers/webhooks.py
Labels: improvement

#986 :white_check_mark: fix test to work with pytest-xdist
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_wallet_dids.py
  app/tests/e2e/verifier/test_verifier.py
Labels: tests

#985 :arrow_up: Update lock files
  app/poetry.lock
  endorser/poetry.lock
  trustregistry/poetry.lock
  webhooks/poetry.lock
Labels: dependencies

#999 :wrench: Modify SSE Manager env var defaults, and make setting of locks configurable
  .vscode/settings.json
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/util/webhooks.py
  endorser/services/endorsement_processor.py
  scripts/k6/libs/functions.js
  scripts/k6/scenarios/revoke-credentials.js
  shared/constants.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/webhooks_redis_service.py
  webhooks/tests/routes/test_sse.py
  webhooks/tests/services/test_acapy_events_processor.py
Labels: improvement

#989 ✨ Add ordering functionality to fetching of askar records
  app/poetry.lock
  app/pyproject.toml
  app/routes/admin/tenants.py
  app/routes/connections.py
  app/routes/issuer.py
  app/routes/verifier.py
  app/services/issuer/acapy_issuer.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/verifier/test_get_records_paginated.py
  app/tests/routes/connections/test_get_connections.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/verifier/test_verifier.py
  app/util/pagination.py
  docker-compose.yaml
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: enhancement, epic
