Repository didx-xyz/acapy-cloud, pull requests merged in 2024-05, with the labels that each got.

#780 :test_tube: Initial regression testing framework
  app/routes/admin/tenants.py
  app/tests/conftest.py
  app/tests/e2e/conftest.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_messaging.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/test_webhooks.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/fixtures/__init__.py
  app/tests/fixtures/credentials.py
  app/tests/fixtures/definitions.py
  app/tests/fixtures/dids.py
  app/tests/fixtures/member_acapy_clients.py
  app/tests/fixtures/member_async_clients.py
  app/tests/fixtures/member_connections.py
  app/tests/fixtures/member_wallets.py
  app/tests/test_util_webhooks.py
  app/tests/util/client.py
  app/tests/util/connections.py
  app/tests/util/definitions.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/member_wallets.py
  app/tests/util/regression_testing.py
  app/tests/util/trust_registry.py
  app/tests/util/webhooks.py
  shared/util/rich_async_client.py
  webhooks/tests/e2e/conftest.py
  webhooks/tests/e2e/test_sse.py
  webhooks/tests/e2e/test_webhooks.py
Labels: tests

#794 :memo: Update openapi spec
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
Labels: documentation

#795 Regression test revoked credential
  app/tests/e2e/conftest.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/fixtures/credentials.py
Labels: tests

#803 :sparkles: Don't delete the credential when deleting credential exchange record
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
Labels: improvement

#802 :art: rename `credential_id` to `credential_exchange_id` and :warning: mark old field as deprecated
  app/routes/issuer.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_revocation.py
  app/tests/fixtures/credentials.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/issuer/test_issuer.py
  app/util/credentials.py
  docs/Common Steps.md
  docs/examples/5. Issue Credential.md
  shared/models/credential_exchange.py
  webhooks/tests/test_webhook_models.py
Labels: improvement, refactor

#777 🎨 update revoke credential request body and ✅ add tests with auto-publish true
  app/models/issuer.py
  app/routes/issuer.py
  app/services/revocation_registry.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/fixtures/credentials.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/test_revocation_registry.py
Labels: enhancement

#778 Update issuer endpoint docs
  app/routes/issuer.py
Labels: documentation

#792 Update Connections doc strings
  app/models/connections.py
  app/routes/connections.py
  app/tests/e2e/test_connections.py
Labels: documentation

#805 Regression test valid credential
  app/tests/e2e/conftest.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/fixtures/credentials.py
  app/tests/util/regression_testing.py
Labels: tests

#808 :art: Update trust registry models
  app/models/tenants.py
  app/models/trust_registry.py
  app/routes/admin/tenants.py
  app/routes/trust_registry.py
  app/services/onboarding/tenants.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/services/trust_registry/util/actor.py
  app/services/trust_registry/util/issuer.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/routes/admin_tenants/test_create_tenant.py
  app/tests/services/test_trust_registry.py
  app/tests/services/verifier/test_verifier.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/util/connections.py
  app/tests/util/trust_registry.py
  app/util/acapy_verifier_utils.py
  app/util/extract_validation_error.py
  shared/models/trustregistry.py
  trustregistry/tests/test_crud.py
  trustregistry/tests/test_registry_actors.py
Labels: refactor

#793 Definitions swagger update
  app/models/definitions.py
  app/routes/definitions.py
  app/services/revocation_registry.py
  app/tests/e2e/test_definitions.py
Labels: documentation

#813 :sparkles: Speed up tests by adjusting fixture scope
  app/services/acapy_wallet.py
  app/tests/e2e/test_revocation.py
  app/tests/fixtures/definitions.py
  app/tests/fixtures/member_async_clients.py
  app/tests/fixtures/member_wallets.py
Labels: improvement, tests

#816 :white_check_mark: test coverage for connection routes
  app/routes/connections.py
  app/tests/routes/connections/test_accept_invitation.py
  app/tests/routes/connections/test_create_invitation.py
  app/tests/routes/connections/test_delete_connection.py
  app/tests/routes/connections/test_get_connection_by_id.py
  app/tests/routes/connections/test_get_connections.py
Labels: tests
