Repository didx-xyz/acapy-cloud, pull requests merged in 2024-10, with the labels that each got.

#1095 ⚡💥✨🚀 Replace Redis webhook events with NATS Jetstream
  .github/workflows/continuous-deploy.yml
  .gitignore
  .mise.toml
  app/poetry.lock
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_webhooks.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/fixtures/credentials.py
  app/tests/fixtures/member_async_clients.py
  app/tests/util/sse_listener.py
  docker-compose.yaml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/main.py
  endorser/poetry.lock
  endorser/pyproject.toml
  endorser/services/dependency_injection/container.py
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  endorser/tests/test_main.py
  endorser/tests/test_util_endorsement.py
  endorser/tests/test_util_transaction_record.py
  endorser/util/endorsement.py
  endorser/util/transaction_record.py
  shared/constants.py
  shared/services/nats_jetstream.py
  tilt/cloudapi/Tiltfile
  tilt/cloudapi/nats/templates/job.yaml
  tilt/cloudapi/nats/values.yaml
  tilt/cloudapi/redis.yaml
  trustregistry/poetry.lock
  waypoint/poetry.lock
  waypoint/routers/sse.py
  waypoint/services/dependency_injection/container.py
  waypoint/services/nats_service.py
  waypoint/tests/services/test_nats_service.py
  webhooks/poetry.lock
  webhooks/pyproject.toml
  webhooks/services/acapy_events_processor.py
  webhooks/tests/e2e/test_sse.py
  webhooks/tests/e2e/test_webhooks.py
  webhooks/tests/services/test_acapy_events_processor.py
  webhooks/tests/test_main.py
  webhooks/web/main.py
Labels: enhancement

#902 :wastebasket: Remove v1 protocol version and default to v2
  README.md
  app/models/issuer.py
  app/models/verifier.py
  app/routes/issuer.py
  app/routes/verifier.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/revocation_registry.py
  app/services/verifier/acapy_verifier_v1.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/verifier/test_get_credentials_by_proof_id.py
  app/tests/e2e/verifier/test_get_records_paginated.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_predicate_proofs.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_self_attested.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/fixtures/credentials.py
  app/tests/routes/issuer/test_create_offer.py
  app/tests/routes/issuer/test_get_credential.py
  app/tests/routes/issuer/test_get_credentials.py
  app/tests/routes/issuer/test_publish_revocations.py
  app/tests/routes/issuer/test_request_credential.py
  app/tests/routes/issuer/test_send_credential.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/test_revocation_registry.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/services/verifier/utils.py
  app/util/acapy_issuer_utils.py
  app/util/acapy_verifier_utils.py
  app/util/credentials.py
  docker-compose-ledger.yaml
  docs/Common Steps.md
  docs/examples/5. Issue Credential.md
  docs/examples/7. Verify Credential.md
  docs/examples/9. Verify Revoked Credentials.md
  docs/examples/Requested Predicates/1. Requested Predicates.md
  docs/examples/Restrictions on Proofs/1. Restrictions on Proofs.md
  docs/examples/Self-Attested Attributes/1. Self-Attested Attributes.md
  openapi/tenant-admin-openapi.json
  openapi/tenant-admin-openapi.yaml
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
  scripts/k6/libs/functions.js
  shared/models/credential_exchange.py
  shared/models/presentation_exchange.py
  shared/models/protocol.py
  shared/util/mock_agent_controller.py
  webhooks/models/conversions.py
  webhooks/tests/test_webhook_models.py
Labels: improvement

#1111 :arrow_up: Upgrade `pre-commit` and `black` to latest
  .github/workflows/style-check.yml
  .pre-commit-config.yaml
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1121 :arrow_up: Upgrade poetry version and update lock files
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1124 :pushpin: Pin `xk6` and plugins
  scripts/k6/Dockerfile
Labels: dependencies

#1125 :pushpin: Explicitly pin k6 to `v0.52.0`
  scripts/k6/Dockerfile
Labels: dependencies

#1119 :sparkles: Implement DID Exchange and DID Rotate methods and 🗑️ deprecate connections protocol
  .pylintrc
  app/models/tenants.py
  app/poetry.lock
  app/pyproject.toml
  app/routes/connections.py
  app/tests/e2e/test_did_exchange.py
  app/tests/e2e/test_did_rotate.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/routes/connections/test_accept_did_exchange_request.py
  app/tests/routes/connections/test_create_did_exchange_request.py
  app/tests/routes/connections/test_delete_connection.py
  app/tests/routes/connections/test_did_rotate.py
  app/tests/routes/connections/test_did_rotate_hangup.py
  app/tests/routes/connections/test_reject_did_exchange.py
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  waypoint/poetry.lock
Labels: enhancement

#1122 :bug: Fix endorser Nats connection going stale
  app/services/onboarding/util/register_issuer_did.py
  app/tests/e2e/test_did_exchange.py
  docker-compose.yaml
  endorser/main.py
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  endorser/tests/test_main.py
Labels: bug

#1118 :memo: Update Waypoint doc & SSE docstring
  app/routes/sse.py
  docs/NATS.md
  docs/Webhooks.md
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
Labels: documentation

#1134 :arrow_up: Upgrade ddtrace (2.14.4)
  app/poetry.lock
  endorser/poetry.lock
  trustregistry/poetry.lock
Labels: dependencies

#1136 :arrow_up: Upgrade to our 1.1.1b0 acapy release
  README.md
  app/services/acapy_ledger.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  docs/Aries Cloud API Architecture.md
  docs/Governance as Code.md
  environments/governance-ga/aca-py-agent.default.env
  environments/governance-multitenant/aca-py-agent.default.env
  shared/models/endorsement.py
Labels: enhancement, dependencies

#1138 :bug: fix DidRotate Hangup error
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
Labels: bug

#1137 :zap: Waypoint start time
  app/routes/sse.py
  app/services/event_handling/sse.py
  app/tests/routes/test_sse.py
  app/tests/services/event_handling/test_sse.py
  app/tests/util/sse_listener.py
  waypoint/routers/sse.py
  waypoint/services/nats_service.py
  waypoint/tests/routers/test_waypoint_sse.py
  waypoint/tests/services/test_nats_service.py
Labels: improvement

#1139 :heavy_plus_sign: Add ddtrace to waypoint
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1140 :arrow_up: Upgrade cloudcontroller
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  waypoint/poetry.lock
Labels: dependencies

#1141 :sparkles: Implement retry logic in RichAsyncClient
  shared/util/rich_async_client.py
Labels: bug, enhancement

#1142 :sparkles: improve acapy exception handling
  app/poetry.lock
  app/tests/e2e/test_auth.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  pyproject.toml
  trustregistry/poetry.lock
  waypoint/poetry.lock
Labels: enhancement
