Repository didx-xyz/acapy-cloud, pull requests merged in 2024-03, with the labels that each got.

#679 Bump Mozilla sops action
  .github/workflows/continuous-deploy.yml
Labels: dependencies, github_actions

#680 Enable Redis TLS, Auth, and Clustered in GH Actions
  .github/workflows/continuous-deploy.yml
Labels: bug

#665 Auto Revocation Registry
  app/routes/definitions.py
  app/services/acapy_ledger.py
  app/services/revocation_registry.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_revocation.py
  app/tests/services/test_revocation_registry.py
  app/tests/util/credentials.py
  app/tests/util/definitions.py
  docker-compose.yaml
  endorser/util/endorsement.py
  endorser/util/transaction_record.py
  environments/governance-multitenant/aca-py-agent.default.env
  shared/constants.py
  shared/models/endorsement.py
  webhooks/services/acapy_events_processor.py
  webhooks/tests/test_acapy_events_processor.py
Labels: enhancement

#691 :bug: fix missing group_id in update/get_tenant response
  app/tests/e2e/test_tenants.py
  app/util/tenants.py
Labels: bug

#687 :pushpin: pin von-network version to v1.8.0
  .github/workflows/continuous-deploy.yml
  docker-compose.yaml
Labels: dependencies

#692 :truck: reorganise tests and :construction_worker: update test matrix
  .github/workflows/continuous-deploy.yml
  .pylintrc
  app/.pylintrc
  app/main.py
  app/routes/definitions.py
  app/services/event_handling/__init__.py
  app/services/event_handling/sse_listener.py
  app/services/event_handling/websocket_manager.py
  app/services/onboarding/util/register_issuer_did.py
  app/services/websocket.py
  app/tests/e2e/issuer/did_key_bbs/test_ld_bbs_x.py
  app/tests/e2e/issuer/did_key_ed/test_ld_ed_x.py
  app/tests/e2e/issuer/indy/__init__.py
  app/tests/e2e/issuer/indy/test_v1_indy.py
  app/tests/e2e/issuer/indy/test_v2_indy.py
  app/tests/e2e/issuer/ld_proof/__init__.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/test_trust_registry_integration.py
  app/tests/e2e/verifier/__init__.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/services/event_handling/__init__.py
  app/tests/services/event_handling/test_websocket_manager.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/test_onboarding.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier.py
  app/tests/services/verifier/utils.py
  app/tests/test_util_definitions.py
  app/tests/test_util_did.py
  app/tests/util/credentials.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/webhooks.py
Labels: improvement

#689 :art: modify serialized logs pattern and :sparkles: improve exception handling
  app/exceptions/__init__.py
  app/exceptions/handle_acapy_call.py
  app/routes/connections.py
  app/routes/wallet/credentials.py
  app/routes/wallet/jws.py
  app/routes/wallet/sd_jws.py
  app/tests/e2e/test_wallet_jws.py
  app/tests/e2e/test_wallet_sd_jws.py
  app/util/extract_validation_error.py
  shared/log_config.py
  trustregistry/list_type.py
Labels: improvement

#688 Update proof models
  app/models/verifier.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/services/verifier/utils.py
Labels: bug

#690 :art: Update extra wallet settings in create/update tenant request
  app/models/tenants.py
  app/tests/e2e/test_tenants.py
Labels: improvement

#664 Add query params to get connections and credential/proof exchange records
  app/routes/connections.py
  app/routes/issuer.py
  app/routes/verifier.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/verifier/test_verifier.py
  app/tests/util/ecosystem_connections.py
  docker-compose.yaml
  shared/models/connection_record.py
  shared/models/credential_exchange.py
  shared/models/presentation_exchange.py
Labels: enhancement

#700 :art: Replace SseListeners used in app
  app/routes/connections.py
  app/routes/definitions.py
  app/services/onboarding/issuer.py
  app/services/onboarding/util/register_issuer_did.py
  app/tests/e2e/test_connections.py
  app/tests/exception_handling/__init__.py
  app/tests/exception_handling/test_handle_acapy_call.py
  app/tests/exception_handling/test_handle_model_with_validation.py
  app/tests/services/onboarding/__init__.py
  app/tests/services/onboarding/test_onboarding.py
  app/tests/services/onboarding/test_register_issuer_did.py
  app/util/extract_validation_error.py
  app/util/retry_method.py
  endorser/tests/test_util_endorsement.py
  endorser/tests/test_util_transaction_record.py
  endorser/util/endorsement.py
  endorser/util/transaction_record.py
  shared/models/endorsement.py
  webhooks/services/acapy_events_processor.py
Labels: enhancement

#703 :adhesive_bandage: disable pubsub notification listener in events processors
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  webhooks/services/acapy_events_processor.py
  webhooks/tests/test_acapy_events_processor.py
Labels: bug

#707 :sparkles: obfuscate secret data from webhook logs
  app/util/retry_method.py
  shared/log_config.py
  shared/models/endorsement.py
  shared/services/redis_service.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/webhooks_redis_serivce.py
  webhooks/tests/test_acapy_events_processor.py
  webhooks/tests/test_redis_service.py
Labels: improvement

#708 :bug: Fix double endorsement
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  shared/models/endorsement.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/webhooks_redis_serivce.py
Labels: bug

#709 :wastebasket: Deprecate webhooks endpoint
  app/routes/webhooks.py
  app/services/webhooks.py
  webhooks/services/webhooks_redis_serivce.py
  webhooks/tests/test_redis_service.py
  webhooks/web/routers/webhooks.py
Labels: refactor

#712 :sparkles: Validate wallet_id belongs to group_id in SSE subscriptions
  webhooks/services/sse_manager.py
  webhooks/services/webhooks_redis_serivce.py
  webhooks/tests/test_redis_service.py
  webhooks/tests/test_sse_manager.py
  webhooks/web/routers/sse.py
Labels: improvement

#716 :sparkles: Configure SseListeners in tests with retry logic
  app/tests/e2e/issuer/indy/test_v1_indy.py
  app/tests/e2e/issuer/indy/test_v2_indy.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/test_util_webhooks.py
  app/tests/util/credentials.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/webhooks.py
Labels: improvement

#714 :sparkles: add group_id to websocket subscriptions
  app/routes/websocket_endpoint.py
  app/services/event_handling/websocket_manager.py
  app/services/websocket.py
  app/tests/services/event_handling/test_websocket_manager.py
  webhooks/services/sse_manager.py
  webhooks/services/webhooks_redis_serivce.py
  webhooks/tests/test_redis_service.py
  webhooks/tests/test_sse_manager.py
  webhooks/web/routers/websocket.py
Labels: enhancement

#717 :sparkles: Add `group_id` query parameter to SSE endpoints
  app/routes/sse.py
  app/services/sse.py
Labels: improvement
