Repository didx-xyz/acapy-cloud, pull requests merged in 2024-09, with the labels that each got.

#1006 :memo: Update openapi specs for v3.4.0 release
  openapi/tenant-admin-openapi.json
  openapi/tenant-admin-openapi.yaml
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
Labels: documentation

#1009 :arrow_up: Upgrade fastapi, sqlalchemy, starlette
  app/poetry.lock
  endorser/poetry.lock
  trustregistry/poetry.lock
  webhooks/poetry.lock
Labels: dependencies

#1018 :arrow_up: Upgrade dependencies: fastapi, pydantic
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#954 📝 Add self-attested example docs
  docs/examples/Self-Attested Attributes/1. Self-Attested Attributes.md
Labels: documentation

#826 📝 Requested predicates proofs
  .codacy.yaml
  .editorconfig
  .markdownlint.json
  .vscode/settings.json
  docs/examples/Requested Predicates/1. Requested Predicates.md
Labels: documentation

#955 🧑‍💻 🔨 🔧 👷 Mise, Kind, and Tilt
  .env.example
  .github/workflows/continuous-deploy.yml
  .gitignore
  .mise.toml
  .mise/tasks/kind/create
  .mise/tasks/kind/destroy
  .mise/tasks/kind/install/istio
  .mise/tasks/kind/install/nginx
  .mise/tasks/kind/install/pull-through
  .mise/tasks/kind/install/registry
  .mise/tasks/kind/kind.yaml
  .mise/tasks/poetry/install/app
  .mise/tasks/poetry/install/endorser
  .mise/tasks/poetry/install/trustregistry
  .mise/tasks/poetry/install/webhooks
  .vscode/extensions.json
  README.md
  Tiltfile
  docker-compose-ledger.yaml
  docker-compose.yaml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/webhooks/Dockerfile
  docs/Bootstrap Trust Ecosystem.md
  docs/Common Steps.md
  docs/Governance as Code.md
  docs/Quick Start Guide.md
  docs/README.md
  docs/Trust Registry.md
  docs/Webhooks.md
  docs/examples/1. Onboarding.md
  docs/examples/2. Create Schema.md
  docs/examples/3. Create Credential Definition.md
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/5. Issue Credential.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
  scripts/install_all_dependencies.sh
  tilt/cloudapi/Tiltfile
  tilt/cloudapi/nats/.helmignore
  tilt/cloudapi/nats/Chart.lock
  tilt/cloudapi/nats/Chart.yaml
  tilt/cloudapi/nats/charts/.gitignore
  tilt/cloudapi/nats/templates/job.yaml
  tilt/cloudapi/nats/values.yaml
  tilt/cloudapi/pgadmin.yaml
  tilt/cloudapi/postgres.yaml
  tilt/cloudapi/redis.yaml
  tilt/ingress_nginx/values.yaml
  tilt/istio/gateways.yaml
  tilt/istio/istio.yaml
  tilt/istio/mtls.yaml
  tilt/metrics/Tiltfile
  tilt/utils/Tiltfile
Labels: epic

#784 📝 Add revocation docs
  .codacy.yaml
  .markdownlint.json
  docs/Bootstrap Trust Ecosystem.md
  docs/Common Steps.md
  docs/Governance as Code.md
  docs/Quick Start Guide.md
  docs/Trust Registry.md
  docs/examples/1. Onboarding.md
  docs/examples/2. Create Schema.md
  docs/examples/3. Create Credential Definition.md
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/5. Issue Credential.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
  docs/examples/8. Revoking Credentials.md
  docs/examples/9. Verify Revoked Credentials.md
Labels: documentation

#832 📝 Add restrictions docs
  docs/examples/7. Verify Credential.md
  docs/examples/Restrictions on Proofs/1. Restrictions on Proofs.md
Labels: documentation

#1034 :construction_worker: Add Reset NATS Step
  .github/workflows/continuous-deploy.yml
Labels: github_actions

#1041 :bug: fix log config: create new empty logger for each main module
  shared/log_config.py
Labels: bug

#1043 :rewind: Don't install DDTrace on Agents
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
Labels: bug

#1048 :arrow_up: Update dependencies
  .mise.toml
  .mise/tasks/poetry/install/waypoint
  .mise/tasks/poetry/update/app
  .mise/tasks/poetry/update/endorser
  .mise/tasks/poetry/update/trustregistry
  .mise/tasks/poetry/update/waypoint
  .mise/tasks/poetry/update/webhooks
  app/poetry.lock
  endorser/poetry.lock
  scripts/update_lock_files.sh
  trustregistry/poetry.lock
  waypoint/poetry.lock
  waypoint/pyproject.toml
  webhooks/poetry.lock
Labels: dependencies

#1050 :construction_worker: Add Style Check for Tiltfiles
  .github/workflows/style-check.yml
Labels: github_actions

#1066 :arrow_up: Upgrade `fastapi`, `anyio` and `pylint`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#1053 🧑‍💻 Programmatically detect IP address
  .mise.toml
  Tiltfile
  tilt/cloudapi/Tiltfile
  tilt/utils/Tiltfile
Labels: enhancement

#1075 :heavy_plus_sign: :memo: Disable Redoc, replace Swagger with Scalar
  app/main.py
  app/poetry.lock
  app/pyproject.toml
  endorser/main.py
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/main.py
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/main.py
  waypoint/poetry.lock
  waypoint/pyproject.toml
  waypoint/routers/sse.py
Labels: documentation, nice-to-have

#1094 :arrow_up: Upgrade dependencies: `uvicorn`, `aiohttp`, `ddtrace`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies
