Repository didx-xyz/acapy-cloud, pull requests merged in 2024-04, with the labels that each got.

#718 :white_check_mark: Test coverage for SSE service
  app/routes/sse.py
  app/services/event_handling/sse.py
  app/tests/e2e/issuer/indy/test_v1_indy.py
  app/tests/e2e/issuer/indy/test_v2_indy.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/routes/__init__.py
  app/tests/routes/test_sse.py
  app/tests/services/__init__.py
  app/tests/services/event_handling/test_sse.py
  app/tests/util/sse_listener.py
  app/tests/util/webhooks.py
  requirements.dev.txt
Labels: improvement

#723 :sparkles: add `look_back` query param to SSE routes
  app/routes/sse.py
  app/services/event_handling/sse.py
  app/tests/e2e/issuer/indy/test_v1_indy.py
  app/tests/e2e/issuer/indy/test_v2_indy.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/routes/test_sse.py
  app/tests/services/event_handling/test_sse.py
  app/tests/test_util_webhooks.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/sse_listener.py
  app/tests/util/webhooks.py
  shared/constants.py
  webhooks/services/sse_manager.py
  webhooks/web/routers/sse.py
Labels: enhancement

#724 :pencil2: Resolve typos
  .vscode/settings.json
  app/models/tenants.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/tests/e2e/conftest.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_messaging.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/exception_handling/test_handle_acapy_call.py
  app/tests/services/test_revocation_registry.py
  app/tests/util/ecosystem_connections.py
  app/tests/util/member_acapy_clients.py
  app/tests/util/member_async_clients.py
  app/tests/util/member_wallets.py
  app/tests/util/trust_registry.py
  app/util/acapy_verifier_utils.py
  app/util/string.py
  endorser/tests/test_endorser_processor.py
  endorser/tests/test_util_endorsement.py
  endorser/util/transaction_record.py
  shared/models/webhook_events/payloads.py
  trustregistry/tests/test_actor.py
  trustregistry/tests/test_main.py
  trustregistry/tests/test_models.py
  trustregistry/tests/test_schema.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/dependency_injection/container.py
  webhooks/services/sse_manager.py
  webhooks/services/webhooks_redis_service.py
  webhooks/tests/test_acapy_events_processor.py
  webhooks/tests/test_redis_service.py
  webhooks/util/event_generator_wrapper.py
  webhooks/web/routers/webhooks.py
Labels: improvement

#729 :memo: Update websocket documentation to include new endpoint
  app/main.py
Labels: documentation, improvement

#730 :lock: Forbid wallet actions if wallet doesn't belong to group
  app/routes/admin/tenants.py
  app/routes/sse.py
  app/routes/websocket_endpoint.py
  app/services/onboarding/tenants.py
  app/tests/e2e/test_tenants.py
  app/util/tenants.py
  webhooks/web/routers/sse.py
Labels: bug, enhancement

#731 📝 Update tenant-admin Swagger docs to include CloudAPI description
  app/main.py
Labels: documentation

#589 ✅ Tests: parametrize protocol version in issuer tests
  .vscode/settings.json
  app/exceptions/__init__.py
  app/tests/conftest.py
  app/tests/e2e/issuer/indy/__init__.py
  app/tests/e2e/issuer/indy/test_v2_indy.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/services/test_trust_registry.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/services/verifier/utils.py
  app/tests/util/member_async_clients.py
  app/util/acapy_verifier_utils.py
  webhooks/services/sse_manager.py
Labels: improvement

#732 :adhesive_bandage: Invalidate proof if no associated schema_ids found
  app/routes/websocket_endpoint.py
  app/tests/services/verifier/test_verifier_utils.py
  app/util/acapy_verifier_utils.py
  trustregistry/registry/registry_schemas.py
Labels: improvement

#733 :arrow_up: Upgrade pydantic and cloudcontroller
  .github/workflows/continuous-deploy.yml
  app/requirements.txt
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/webhooks/Dockerfile
  endorser/requirements.txt
  requirements.dev.txt
  trustregistry/requirements.txt
  webhooks/requirements.txt
Labels: dependencies

#735 :adhesive_bandage: Fix WebSocket callback function
  app/services/event_handling/websocket_manager.py
Labels: bug

#738 :white_check_mark: Test coverage for admin-tenants route
  app/routes/admin/tenants.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/routes/admin_tenants/test_create_tenant.py
  app/tests/routes/admin_tenants/test_delete_tenant.py
  app/tests/routes/admin_tenants/test_get_tenant.py
  app/tests/routes/admin_tenants/test_get_tenants.py
  app/tests/routes/admin_tenants/test_get_wallet_auth_token.py
  app/tests/routes/admin_tenants/test_update_tenant.py
  shared/models/endorsement.py
Labels: testing

#746 :bug: Fix race condition when creating credential definitions
  app/routes/definitions.py
Labels: bug

#745 :white_check_mark: Test coverage for webhooks SSE route
  webhooks/tests/routes/test_sse.py
  webhooks/web/routers/sse.py
Labels: tests

#747 :adhesive_bandage: Fix wallet access being restricted when group_id is null
  app/util/tenants.py
Labels: bug

#748 :white_check_mark: Enhanced test coverage for webhooks service
  shared/constants.py
  webhooks/services/dependency_injection/container.py
  webhooks/tests/e2e/test_sse.py
  webhooks/tests/routes/test_sse.py
  webhooks/tests/routes/test_webhooks.py
  webhooks/tests/services/__init__.py
  webhooks/tests/services/test_acapy_events_processor.py
  webhooks/tests/services/test_sse_manager.py
  webhooks/tests/services/test_webhooks_redis_service.py
  webhooks/tests/test_main.py
  webhooks/web/main.py
  webhooks/web/routers/sse.py
  webhooks/web/routers/webhooks.py
Labels: tests

#750 :sparkles: Implement temporary endpoint to patch wallets with old group_id
  app/models/tenants.py
  app/routes/admin/tenants.py
  app/services/onboarding/tenants.py
Labels: bug, improvement

#751 :rewind: Remove wallet-patch endpoint and revert valid group assertion
  app/routes/admin/tenants.py
  app/util/tenants.py
Labels: refactor

#757 Unit tests for trustregistry.crud
  trustregistry/tests/e2e/__init__.py
  trustregistry/tests/e2e/test_actor.py
  trustregistry/tests/e2e/test_main.py
  trustregistry/tests/e2e/test_schema.py
  trustregistry/tests/test_crud.py
Labels: tests

#753 ✅ Remove sleeps from public did tests
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/verifier/test_verifier.py
Labels: tests

#759 Test trust registry endpoints
  trustregistry/tests/test_registry_actors.py
  trustregistry/tests/test_registry_schema.py
Labels: tests

#762 :white_check_mark: Test coverage for verifier service
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/utils.py
Labels: tests

#715 Add Lago billing manager
  .vscode/settings.json
  endorser/tests/test_endorser_processor.py
  shared/constants.py
  webhooks/models/billing_payloads.py
  webhooks/models/conversions.py
  webhooks/services/acapy_events_processor.py
  webhooks/services/billing_manager.py
  webhooks/services/dependency_injection/container.py
  webhooks/services/webhooks_redis_service.py
  webhooks/tests/services/test_acapy_events_processor.py
  webhooks/tests/services/test_sse_manager.py
  webhooks/tests/test_billing_manager.py
  webhooks/tests/test_main.py
  webhooks/web/main.py
Labels: enhancement

#763 :memo: Add openapi specs to project
  openapi/tenant-admin-openapi.json
  openapi/tenant-admin-openapi.yaml
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
Labels: documentation

#734 :arrow_up: Upgrade to latest cloudcontroller
  app/requirements.txt
  endorser/requirements.txt
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
  webhooks/requirements.txt
Labels: dependencies

#764 Added test for `StringList` type decorator
  trustregistry/tests/test_list_type.py
Labels: tests

#766 Add tests for `trustregistry/main.py`
  trustregistry/tests/test_main.py
Labels: tests

#768 Added tests for `trustregistry/db.py`
  trustregistry/tests/test_db.py
  trustregistry/tests/test_registry_actors.py
Labels: tests

#769 :white_check_mark: Test coverage for app.models
  app/models/tenants.py
  app/models/verifier.py
  app/tests/models/__init__.py
  app/tests/models/test_issuer.py
  app/tests/models/test_jsonld.py
  app/tests/models/test_oob.py
  app/tests/models/test_tenants.py
  app/tests/models/test_verifier.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
Labels: tests

#772 :bug: fix ValidationError exception handling
  app/main.py
Labels: bug

#776 :sparkles: strip protocol prefix from cred ex id in revocation service
  app/services/revocation_registry.py
  app/util/credentials.py
Labels: improvement

#783 Fix reject proof request
  app/models/verifier.py
  app/routes/verifier.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier.py
  shared/models/presentation_exchange.py
Labels: bug

#789 :art: Cleanup and parametrize verifier tests
  app/models/verifier.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/models/test_verifier.py
  app/tests/util/credentials.py
  app/tests/util/definitions.py
  app/tests/util/verifier.py
Labels: tests
