Repository didx-xyz/acapy-cloud, pull requests merged in 2024-11, with the labels that each got.

#1157 :arrow_up: Upgrade `pytest-cov`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#814 📝 Update wallet credentials docstrings
  app/models/wallet.py
  app/routes/wallet/credentials.py
Labels: documentation

#1169 ✅ Test limit and offset params on get credentials
  app/tests/e2e/conftest.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/fixtures/credentials.py
Labels: tests

#1135 :memo: Trust registry docs
  .vscode/extensions.json
  docs/Trust Registry.md
Labels: documentation

#1183 ⬆️ Upgrade ACA-Py and ✨ add NATS reconnect logic
  app/poetry.lock
  app/pyproject.toml
  app/routes/verifier.py
  app/routes/wallet/credentials.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  endorser/services/endorsement_processor.py
  pyproject.toml
  shared/services/nats_jetstream.py
  shared/util/rich_async_client.py
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1191 :arrow_up: Update lock files
  app/poetry.lock
  endorser/poetry.lock
  trustregistry/poetry.lock
  waypoint/poetry.lock
Labels: dependencies

#1192 :bug: 🧑‍💻 Fix Mise Tasks
  .github/workflows/continuous-deploy.yml
  .mise.toml
  README.md
Labels: bug

#817 📝 Update docstrings wallet/dids
  app/models/wallet.py
  app/routes/wallet/dids.py
  app/tests/routes/wallet/dids/test_create_did.py
Labels: documentation

#824 📝 💥Swagger tenant admin
  app/routes/admin/tenants.py
  app/tests/e2e/test_auth.py
  app/tests/e2e/test_tenants.py
  app/tests/routes/admin_tenants/test_get_wallet_auth_token.py
  scripts/k6/main.js
  scripts/k6/scenarios/delete-holders.js
  scripts/k6/scenarios/delete-issuers.js
Labels: documentation

#818 📝 Swagger updates wallet/jws
  app/models/jws.py
  app/routes/wallet/jws.py
  app/routes/wallet/sd_jws.py
  app/tests/models/test_jws.py
  app/tests/routes/wallet/jws/test_sign_jws.py
  app/tests/routes/wallet/jws/test_verify_jws.py
  app/tests/routes/wallet/sd_jws/test_sign_sd_jws.py
  app/tests/routes/wallet/sd_jws/test_verify_sd_jws.py
Labels: documentation

#1195 :sparkles: `save_exchange_record` should be Optional
  app/models/issuer.py
  app/models/verifier.py
  app/routes/issuer.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/verifier/test_verifier.py
  app/util/save_exchange_record.py
Labels: enhancement

#1196 :sparkles: Add `save_exchange_record` to request_credential
  app/routes/issuer.py
  app/services/issuer/acapy_issuer.py
  app/services/issuer/acapy_issuer_v2.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/routes/issuer/test_request_credential.py
  app/tests/services/issuer/test_issuer.py
  app/util/save_exchange_record.py
Labels: enhancement

#1198 :arrow_up: Upgrade `aiohttp`, `uvicorn`, `ddtrace`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1204 :arrow_up: Upgrade `pydantic` and `pyjwt`
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1212 :arrow_up: Upgrade `httpx`
  app/poetry.lock
  app/pyproject.toml
  app/tests/util/client.py
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies
