Repository didx-xyz/acapy-cloud, pull requests merged in 2024-07, with the labels that each got.

#842 Create a service for definitions endpoints
  app/routes/definitions.py
  app/services/definitions/__init__.py
  app/services/definitions/credential_definition_publisher.py
  app/services/definitions/credential_definitions.py
  app/services/definitions/schema_publisher.py
  app/services/definitions/schemas.py
  app/services/trust_registry/schemas.py
  app/tests/services/test_trust_registry.py
  app/util/assert_public_did.py
  app/util/check_endorser_connection.py
  app/util/transaction_acked.py
  trustregistry/registry/registry_schemas.py
  trustregistry/tests/e2e/test_schema.py
  trustregistry/tests/test_registry_schema.py
Labels: improvement

#861 :arrow_up: ACA-Py 1.0.0rc4
  app/requirements.txt
  docker-compose.yaml
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/requirements.txt
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
  webhooks/requirements.txt
Labels: dependencies

#850 :sparkles: Pagination support for fetching wallets, connections, cred ex and proof records
  app/routes/admin/tenants.py
  app/routes/connections.py
  app/routes/issuer.py
  app/routes/verifier.py
  app/services/issuer/acapy_issuer_v1.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/verifier/test_get_records_paginated.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/routes/connections/test_get_connections.py
  app/tests/services/issuer/test_acapy_issuer_v1.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/verifier/test_verifier.py
  app/util/pagination.py
  docker-compose.yaml
Labels: enhancement

#870 :arrow_up: update redis events plugin to latest release
  docker-compose.yaml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
Labels: dependencies

#857 Definition routes/services unit tests
  app/services/definitions/schema_publisher.py
  app/services/definitions/schemas.py
  app/tests/routes/definitions/test_create_credential_definition.py
  app/tests/routes/definitions/test_create_schema.py
  app/tests/routes/definitions/test_get_credential_defifnition.py
  app/tests/routes/definitions/test_get_credential_definition_by_id.py
  app/tests/routes/definitions/test_get_schema_by_id.py
  app/tests/routes/definitions/test_get_schemas.py
  app/tests/services/definitions/credential_definition/test_create_cred_def.py
  app/tests/services/definitions/credential_definition/test_get_cred_def.py
  app/tests/services/definitions/credential_definitions_publisher.py/test_publisher.py
  app/tests/services/definitions/schema_publisher/test_schema_publisher.py
  app/tests/services/definitions/schemas/test_create_schemas.py
  app/tests/services/definitions/schemas/test_get_schemas_as_governance.py
  app/tests/services/definitions/schemas/test_get_schemas_as_tenant.py
  app/tests/services/definitions/schemas/test_get_schemas_by_id.py
Labels: tests

#878 :white_check_mark: ensure test tenants are deleted upon test failure
  app/tests/e2e/test_tenants.py
  shared/constants.py
Labels: tests

#879 :white_check_mark: adjust sleep durations in tests
  app/routes/issuer.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
Labels: tests

#863 :sparkles: better dependency management with Poetry
  .dockerignore
  .github/dependabot.yml
  .github/workflows/continuous-deploy.yml
  .github/workflows/style-check.yml
  .isort.cfg
  .python-version
  README.md
  app/poetry.lock
  app/pyproject.toml
  app/requirements.txt
  app/setup.cfg
  app/setup.py
  docker-compose.yaml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/webhooks/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  endorser/requirements.txt
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/install_all_dependencies.sh
  scripts/update_lock_files.sh
  setup.cfg
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  trustregistry/requirements.txt
  trustregistry/setup.cfg
  webhooks/poetry.lock
  webhooks/pyproject.toml
  webhooks/requirements.txt
Labels: enhancement, dependencies, nice-to-have

#900 :arrow_up: Bulk dependency upgrades
  .github/workflows/continuous-deploy.yml
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  webhooks/poetry.lock
  webhooks/pyproject.toml
Labels: dependencies

#898 :bug: Fix scanning of redis keys
  shared/services/redis_service.py
Labels: bug

#897 👷 K6
  .github/workflows/continuous-deploy.yml
  .gitignore
  scripts/k6/Dockerfile
  scripts/k6/README.md
  scripts/k6/auth.js
  scripts/k6/create-credentials.js
  scripts/k6/create-holders.js
  scripts/k6/create-invitation.js
  scripts/k6/create-proof.js
  scripts/k6/delete-holders.js
  scripts/k6/env.sh
  scripts/k6/main.js
  scripts/k6/run_tests.sh
  scripts/k6/tenant.js
Labels: enhancement, improvement
