Repository didx-xyz/acapy-cloud, pull requests merged in 2024-02, with the labels that each got.

#636 Fix revocation
  app/models/issuer.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/jsonld.py
  app/routes/wallet/credentials.py
  app/routes/wallet/dids.py
  app/services/revocation_registry.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_credentials.py
  app/tests/e2e/test_revocation.py
  app/tests/services/test_revocation_registry.py
Labels: enhancement

#644 :arrow_up: Use latest `acapy-wallet-groups-plugin`
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
Labels: dependencies

#650 Update docs
  app/main.py
  docs/Bootstrap Trust Ecosystem.md
  docs/Common Steps.md
  docs/Governance as Code.md
  docs/Quick Start Guide.md
  docs/README.md
  docs/Webhooks.md
  docs/examples/1. Onboarding.md
  docs/examples/2. Create Schema.md
  docs/examples/3. Create Credential Definition.md
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/5. Issue Credential.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
Labels: documentation

#651 :ambulance: Hotfix: handle redis pubsub connection error
  webhooks/dependencies/sse_manager.py
Labels: bug

#657 :sparkles: Implement JWS and SD-JWS sign and verify routes
  app/main.py
  app/models/jws.py
  app/models/sd_jws.py
  app/routes/wallet/jws.py
  app/routes/wallet/sd_jws.py
  app/tests/e2e/test_wallet_jws.py
  app/tests/e2e/test_wallet_sd_jws.py
Labels: enhancement

#658 :art: Minor code cleanup
  .github/workflows/continuous-deploy.yml
  app/models/definitions.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/tests/e2e/test_credentials.py
  app/util/retry_method.py
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  manage
Labels: improvement
