Repository didx-xyz/acapy-cloud, pull requests merged in 2024-06, with the labels that each got.

#804 Swagger updates message oob
  app/models/oob.py
  app/routes/messaging.py
  app/routes/oob.py
Labels: documentation

#827 Predicate proof tests
  app/services/acapy_ledger.py
  app/services/revocation_registry.py
  app/services/verifier/acapy_verifier_v1.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/verifier/test_predicate_proofs.py
  app/tests/services/test_revocation_registry.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
Labels: tests

#758 :arrow_up: Upgrade ACA-Py version to 0.12.1
  app/main.py
  app/requirements.txt
  app/routes/issuer.py
  app/routes/wallet/jws.py
  app/routes/wallet/sd_jws.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/revocation_registry.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/verifier/test_predicate_proofs.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/fixtures/credentials.py
  app/tests/models/test_issuer.py
  app/tests/services/onboarding/test_onboarding.py
  app/tests/services/onboarding/test_register_issuer_did.py
  app/tests/services/test_acapy_wallet.py
  app/tests/services/test_revocation_registry.py
  app/tests/services/verifier/test_acapy_verifier_v1.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/services/verifier/utils.py
  app/tests/util/connections.py
  app/tests/util/webhooks.py
  docker-compose.yaml
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  docs/Common Steps.md
  endorser/main.py
  endorser/requirements.txt
  shared/constants.py
  trustregistry/main.py
  webhooks/requirements.txt
  webhooks/web/main.py
Labels: enhancement, dependencies

#841 :white_check_mark: test coverage for wallet-dids routes
  app/tests/routes/wallet/dids/test_create_did.py
  app/tests/routes/wallet/dids/test_get_did_endpoint.py
  app/tests/routes/wallet/dids/test_get_public_did.py
  app/tests/routes/wallet/dids/test_list_dids.py
  app/tests/routes/wallet/dids/test_rotate_keypair.py
  app/tests/routes/wallet/dids/test_set_did_endpoint.py
  app/tests/routes/wallet/dids/test_set_public_did.py
Labels: tests

#843 :white_check_mark: test coverage for issuer routes
  app/routes/issuer.py
  app/tests/routes/issuer/test_clear_pending_revocations.py
  app/tests/routes/issuer/test_create_offer.py
  app/tests/routes/issuer/test_get_credential.py
  app/tests/routes/issuer/test_get_credential_revocation_record.py
  app/tests/routes/issuer/test_get_credentials.py
  app/tests/routes/issuer/test_publish_revocations.py
  app/tests/routes/issuer/test_remove_credential_exchange_record.py
  app/tests/routes/issuer/test_request_credential.py
  app/tests/routes/issuer/test_revoke_credential.py
  app/tests/routes/issuer/test_send_credential.py
  app/tests/routes/issuer/test_store_credential.py
Labels: tests

#844 :memo: Update openapi specs
  openapi/tenant-admin-openapi.json
  openapi/tenant-admin-openapi.yaml
  openapi/tenant-openapi.json
  openapi/tenant-openapi.yaml
Labels: documentation

#839 :arrow_up: upgrade to latest ACA-Py build
  app/requirements.txt
  docker-compose.yaml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/requirements.txt
  webhooks/requirements.txt
Labels: dependencies
