Repository didx-xyz/acapy-cloud, pull requests merged in 2025-02, with the labels that each got.

#1305 📝 Add `README.md` to Helm charts
  helm/acapy-cloud/README.md
  helm/acapy-test/README.md
Labels: documentation

#1307 🧑‍💻 Indy Ledger Nodes Helm
  .github/workflows/continuous-deploy.yml
  helm/acapy-cloud/conf/local/ledger-browser.yaml
  helm/ledger-nodes/.helmignore
  helm/ledger-nodes/Chart.yaml
  helm/ledger-nodes/conf/.gitignore
  helm/ledger-nodes/conf/local/values.yaml
  helm/ledger-nodes/templates/_helpers.tpl
  helm/ledger-nodes/templates/configmap.yaml
  helm/ledger-nodes/templates/service-headless.yaml
  helm/ledger-nodes/templates/serviceaccount.yaml
  helm/ledger-nodes/templates/statefulset.yaml
  helm/ledger-nodes/values.yaml
  scripts/k6/run_tests.sh
  scripts/k6/scenarios/revoke-credentials.js
  tilt/acapy-cloud/Tiltfile
Labels: enhancement

#1310 :sparkles: Set uvloop as the default event loop policy
  app/main.py
  app/poetry.lock
  app/pyproject.toml
  endorser/main.py
  endorser/poetry.lock
  endorser/pyproject.toml
  shared/util/set_event_loop_policy.py
  trustregistry/main.py
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/main.py
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: enhancement

#1306 :sparkles::memo: Rename to acapy-cloud, update documentation
  README.md
  Tiltfile
  app/main.py
  app/pyproject.toml
  app/tests/test_main.py
  docs/book.toml
  docs/src/Bootstrap Trust Ecosystem.md
  docs/src/Common Steps.md
  docs/src/Example Flows.md
  docs/src/Governance as Code.md
  docs/src/Quick Start Guide.md
  docs/src/README.md
  docs/src/SUMMARY.md
  docs/src/Webhooks.md
  docs/src/acapy-cloud Architecture.md
  docs/src/examples/1. Onboarding.md
  docs/src/examples/3. Create Credential Definition.md
  docs/src/examples/4. Create Connection with Issuer.md
  docs/src/examples/5. Issue Credential.md
  docs/src/examples/6. Create Connection with Verifier.md
  docs/src/examples/7. Verify Credential.md
  docs/src/examples/8. Revoking Credentials.md
  docs/src/examples/9. Verify Revoked Credentials.md
  docs/src/examples/Requested Predicates/1. Requested Predicates.md
  docs/src/examples/Restrictions on Proofs/1. Restrictions on Proofs.md
  docs/src/examples/Self-Attested Attributes/1. Self-Attested Attributes.md
  endorser/pyproject.toml
  helm/acapy-cloud/Chart.yaml
  helm/acapy-cloud/README.md
  helm/acapy-cloud/conf/local/governance-agent.yaml
  helm/acapy-cloud/conf/local/governance-web.yaml
  helm/acapy-cloud/conf/local/ledger-browser.yaml
  helm/acapy-cloud/conf/local/mediator.yaml
  helm/acapy-cloud/conf/local/multitenant-agent.yaml
  helm/acapy-cloud/conf/local/multitenant-web.yaml
  helm/acapy-cloud/conf/local/public-web.yaml
  helm/acapy-cloud/conf/local/tenant-web.yaml
  helm/acapy-cloud/conf/local/trust-registry.yaml
  helm/acapy-test/README.md
  pyproject.toml
  trustregistry/pyproject.toml
  waypoint/pyproject.toml
Labels: documentation

#1312 :test_tube: Configure xdist group for session fixtures
  .vscode/settings.json
  app/services/onboarding/issuer.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/ld_proof/util.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_did_exchange.py
  app/tests/e2e/test_did_rotate.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/verifier/test_get_credentials_by_proof_id.py
  app/tests/e2e/verifier/test_get_records_paginated.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_predicate_proofs.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_self_attested.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  trustregistry/tests/e2e/test_actor.py
  trustregistry/tests/e2e/test_schema.py
Labels: tests

#1314 :fire: Remove unnecessary tests
  app/tests/e2e/test_definitions.py
  app/tests/util/trust_registry.py
Labels: improvement, tests

#1315 :memo: Update CICD `README.md`
  .github/workflows/README.md
Labels: documentation

#1317 :wrench: Increase `max_connections` for multitenant agent
  helm/acapy-cloud/conf/dev/multitenant-agent-pg-proxy.yaml
  helm/acapy-cloud/conf/dev/multitenant-agent.yaml
  helm/acapy-cloud/conf/local/multitenant-agent-pg-proxy.yaml
  helm/acapy-cloud/conf/local/multitenant-agent.yaml
Labels: bug

#1329 :white_check_mark: Add xdist group to run tests sequentially
  app/tests/e2e/test_wallet_dids.py
  trustregistry/tests/e2e/test_actor.py
  trustregistry/tests/e2e/test_schema.py
Labels: bug, tests

#1332 :truck::memo: Update and move openapi specs
  docs/openapi/tenant-admin-openapi.json
  docs/openapi/tenant-admin-openapi.yaml
  docs/openapi/tenant-openapi.json
  docs/openapi/tenant-openapi.yaml
  scripts/download_openapi_specs.sh
  scripts/k6/README.md
  scripts/k6/scripts/collection_batch.sh
Labels: documentation, enhancement

#1303 :arrow_up: Upgrade acapy image to 1.2.1
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/agents/Dockerfile
  docs/openapi/tenant-admin-openapi.json
  docs/openapi/tenant-admin-openapi.yaml
  endorser/poetry.lock
  endorser/pyproject.toml
Labels: dependencies

#1333 :arrow_up: Upgrade Poetry `2.0.1` to `2.1.1`
  .github/workflows/sonarcloud.yml
  .mise.toml
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/app/Dockerfile
  dockerfiles/endorser/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies, python

#1341 :arrow_up: Upgrade Local/Dev Infra
  helm/acapy-cloud.yaml.gotmpl
  tilt/acapy-cloud/Tiltfile
  tilt/metrics/Tiltfile
Labels: dependencies
