Repository didx-xyz/acapy-cloud, pull requests merged in 2025-03, with the labels that each got.

#1350 :arrow_up: :construction_worker: Bump Mise, DDTrace, and unpin Tailscale
  .github/workflows/cicd.yml
  helm/acapy-cloud/values.yaml
Labels: dependencies, github_actions

#1349 :bug: Add `credential_id` on matching proofs
  app/models/verifier.py
  app/routes/verifier.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/services/verifier/test_verifier.py
  docs/openapi/tenant-openapi.json
  docs/openapi/tenant-openapi.yaml
Labels: bug

#1331 🐛 Waypoint wait for consumer to be ready
  shared/constants.py
  shared/services/nats_jetstream.py
  waypoint/poetry.lock
  waypoint/pyproject.toml
  waypoint/services/nats_service.py
  waypoint/tests/services/test_nats_service.py
Labels: bug, improvement

#1353 :arrow_up: 🧑‍💻 Update NATS Chart.lock
  helm/nats/Chart.lock
Labels: dependencies

#1366 :test_tube: Rename Indy test fixtures
  app/tests/conftest.py
  app/tests/e2e/conftest.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_did_exchange.py
  app/tests/e2e/test_did_rotate.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/test_proof_request_models.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/test_trust_registry.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/verifier/test_get_credentials_by_proof_id.py
  app/tests/e2e/verifier/test_get_records_paginated.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_predicate_proofs.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_self_attested.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/e2e/verifier/test_verifier_oob.py
  app/tests/fixtures/credentials.py
  app/tests/fixtures/definitions.py
  app/tests/fixtures/dids.py
  app/tests/fixtures/member_acapy_clients.py
  app/tests/fixtures/member_async_clients.py
  app/tests/fixtures/member_connections.py
  app/tests/fixtures/member_wallets.py
  app/tests/util/tenants.py
Labels: testing

#1354 ✨1 Anoncreds schemas
  app/models/definitions.py
  app/routes/definitions.py
  app/services/definitions/schema_publisher.py
  app/services/definitions/schemas.py
  app/tests/routes/definitions/test_get_schema_by_id.py
  app/tests/routes/definitions/test_get_schemas.py
  app/tests/services/definitions/schema_publisher/test_schema_publisher_anoncreds.py
  app/tests/services/definitions/schemas/test_create_schemas.py
  app/tests/services/definitions/schemas/test_get_schemas_as_governance.py
  app/tests/services/definitions/schemas/test_get_schemas_as_tenant.py
  app/tests/services/definitions/schemas/test_get_schemas_by_id.py
  app/util/definitions.py
  app/util/tenants.py
Labels: enhancement

#1355 ✨ Anoncreds credential definitions
  app/routes/definitions.py
  app/services/definitions/credential_definition_publisher.py
  app/services/definitions/credential_definitions.py
  app/services/definitions/schemas.py
  app/services/revocation_registry.py
  app/tests/routes/definitions/test_get_credential_definition.py
  app/tests/routes/definitions/test_get_credential_definition_by_id.py
  app/tests/services/definitions/credential_definition/test_create_cred_def.py
  app/tests/services/definitions/credential_definition/test_get_cred_def.py
  app/tests/services/definitions/credential_definitions_publisher/test_publisher.py
  app/util/definitions.py
  app/util/tenants.py
  endorser/main.py
  endorser/services/endorser_config.py
  endorser/tests/conftest.py
  endorser/tests/test_endorser_config.py
  endorser/tests/test_main.py
  endorser/tests/test_util_transaction_record.py
  endorser/util/transaction_record.py
Labels: enhancement

#1358 :sparkles: Anoncreds issuance support
  .vscode/settings.json
  app/models/issuer.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/routes/revocation.py
  app/services/acapy_ledger.py
  app/services/definitions/credential_definition_publisher.py
  app/services/definitions/credential_definitions.py
  app/services/definitions/schemas.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/revocation_registry.py
  app/tests/e2e/test_did_rotate.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/models/test_issuer.py
  app/tests/routes/issuer/test_create_offer.py
  app/tests/routes/issuer/test_send_credential.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/issuer/test_issuer.py
  app/tests/services/onboarding/test_register_issuer_did.py
  app/tests/services/test_acapy_ledger.py
  app/tests/services/test_trust_registry.py
  app/tests/test_util_wallet_type_checks.py
  app/util/definitions.py
  app/util/tenants.py
  app/util/valid_issuer.py
  app/util/wallet_type_checks.py
  endorser/tests/test_util_transaction_record.py
  shared/models/credential_exchange.py
  shared/tests/models/__init__.py
  shared/tests/models/test_credential_exchange.py
  shared/util/mock_agent_controller.py
Labels: enhancement

#1359 ✨ Anoncreds verifier support
  .vscode/settings.json
  app/models/verifier.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/models/test_verifier.py
  app/tests/services/onboarding/test_onboarding.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier.py
  app/tests/services/verifier/utils.py
  app/util/acapy_verifier_utils.py
  shared/models/presentation_exchange.py
  shared/tests/models/test_presentation_exchange.py
Labels: enhancement

#1382 :sparkles: Allow anoncreds issuers to create schemas
  app/routes/definitions.py
  app/services/definitions/schemas.py
  app/tests/conftest.py
  app/tests/routes/definitions/test_create_schema.py
  app/tests/services/definitions/schemas/test_create_schemas.py
  shared/util/mock_agent_controller.py
Labels: enhancement

#1381 :test_tube: Add anoncreds test fixtures
  app/services/definitions/schemas.py
  app/tests/conftest.py
  app/tests/e2e/conftest.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/verifier/test_proof_revoked_credential.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/fixtures/credentials.py
  app/tests/fixtures/definitions.py
  app/tests/fixtures/member_acapy_clients.py
  app/tests/fixtures/member_async_clients.py
  app/tests/fixtures/member_wallets.py
  app/tests/routes/definitions/test_create_schema.py
  app/tests/services/definitions/schemas/test_create_schemas.py
  app/tests/util/regression_testing.py
Labels: tests

#1383 📝 Update docstrings re: anoncreds wallet types
  app/routes/admin/tenants.py
  app/routes/issuer.py
  app/routes/revocation.py
  app/routes/verifier.py
Labels: documentation

#1388 :sparkles: Endorse Schema transactions
  app/services/definitions/schemas.py
  endorser/tests/test_util_endorsement.py
  endorser/util/endorsement.py
  endorser/util/transaction_record.py
  shared/models/endorsement.py
Labels: enhancement

#1384 :test_tube: Create anoncreds schema in e2e tests
  app/services/definitions/schema_publisher.py
  app/services/definitions/schemas.py
  app/tests/e2e/test_definitions.py
  app/tests/fixtures/definitions.py
  app/util/did.py
Labels: tests

#1393 :test_tube: Configure wallet-type in regression fixtures
  app/tests/fixtures/member_wallets.py
  app/tests/util/regression_testing.py
Labels: tests

#1391 :white_check_mark: e2e test for fetching AnonCreds schema
  app/tests/e2e/test_definitions.py
  app/tests/fixtures/member_wallets.py
Labels: tests

#1395 :test_tube: e2e test for creating AnonCreds cred def
  app/tests/e2e/test_definitions.py
  dockerfiles/agents/Dockerfile
Labels: tests

#1397 :test_tube: Test AnonCreds credentials e2e
  app/models/issuer.py
  app/routes/definitions.py
  app/routes/issuer.py
  app/services/definitions/credential_definitions.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/revocation_registry.py
  app/tests/conftest.py
  app/tests/e2e/issuer/test_anoncreds_credentials.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_get_records_paginated.py
  app/tests/fixtures/member_connections.py
  app/tests/models/test_issuer.py
  app/tests/routes/definitions/test_create_schema.py
  app/tests/routes/issuer/test_create_offer.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/test_revocation_registry.py
Labels: tests

#1399 :test_tube: Add AnonCreds credential fixtures
  app/tests/e2e/conftest.py
  app/tests/fixtures/credentials.py
  app/tests/routes/definitions/test_create_credential_definition.py
Labels: tests

#1416 :arrow_up: Upgrade dependencies
  .mise.toml
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1419 :heavy_minus_sign: Remove and replace `assertpy`
  .vscode/settings.json
  app/poetry.lock
  app/pyproject.toml
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_bbs.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_key_ed25519.py
  app/tests/e2e/issuer/ld_proof/test_ld_proof_did_sov.py
  app/tests/e2e/issuer/test_anoncreds_credentials.py
  app/tests/e2e/issuer/test_connections_use_public_did.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_definitions.py
  app/tests/e2e/test_did_exchange.py
  app/tests/e2e/test_did_rotate.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_messaging.py
  app/tests/e2e/test_oob.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry.py
  app/tests/e2e/test_wallet_dids.py
  app/tests/services/issuer/test_acapy_issuer_v2.py
  app/tests/services/onboarding/test_onboarding.py
  app/tests/services/test_acapy_ledger.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/test_util_definitions.py
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies, tests

#1417 :bug: Fix ledger DID endpoint rewrites
  dockerfiles/agents/Dockerfile
Labels: bug

#1427 :technologist: :arrow_up: Bump Ingress Nginx
  .mise/tasks/kind/install/nginx
Labels: dependencies
