Repository didx-xyz/acapy-cloud, pull requests merged in 2025-01, with the labels that each got.

#1257 :arrow_up: Upgrade anyio and update lock files
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1258 :arrow_up: Upgrade poetry to 2.0
  .github/workflows/sonarcloud.yml
  .mise.toml
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1262 :sparkles: Update datetime formats in serialized logs
  .vscode/settings.json
  shared/log_config.py
Labels: enhancement

#1263 :art: Clean up waypoint service and look_back defaults
  .vscode/settings.json
  app/poetry.lock
  app/pyproject.toml
  app/routes/admin/tenants.py
  app/tests/e2e/test_auth.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_tenants.py
  app/tests/util/sse_listener.py
  app/tests/util/webhooks.py
  waypoint/routers/sse.py
  waypoint/services/nats_service.py
Labels: enhancement

#1133 :arrow_up: Upgrade to python 3.13
  .github/workflows/sonarcloud.yml
  .github/workflows/style-check.yml
  .mise.toml
  .pylintrc
  README.md
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1261 📝Update connection examples
  docs/examples/4. Create Connection with Issuer.md
  docs/examples/6. Create Connection with Verifier.md
  docs/examples/7. Verify Credential.md
Labels: documentation

#1264 📝Mdbook
  .codacy.yaml
  .github/workflows/mdbook-deploy.yml
  .vscode/settings.json
  docs/.gitignore
  docs/book.toml
  docs/src/Aries Cloud API Architecture.md
  docs/src/Bootstrap Trust Ecosystem.md
  docs/src/Common Steps.md
  docs/src/Example Flows.md
  docs/src/Governance as Code.md
  docs/src/NATS.md
  docs/src/Quick Start Guide.md
  docs/src/README.md
  docs/src/SUMMARY.md
  docs/src/Trust Registry.md
  docs/src/Webhooks.md
  docs/src/examples/1. Onboarding.md
  docs/src/examples/2. Create Schema.md
  docs/src/examples/3. Create Credential Definition.md
  docs/src/examples/4. Create Connection with Issuer.md
  docs/src/examples/5. Issue Credential.md
  docs/src/examples/6. Create Connection with Verifier.md
  docs/src/examples/7. Verify Credential.md
  docs/src/examples/8. Revoking Credentials.md
  docs/src/examples/9. Verify Revoked Credentials.md
  docs/src/examples/Requested Predicates/1. Requested Predicates.md
  docs/src/examples/Restrictions on Proofs/1. Restrictions on Proofs.md
  docs/src/examples/Self-Attested Attributes/1. Self-Attested Attributes.md
Labels: documentation

#1260 :test_tube: Improve test stability
  .vscode/settings.json
  app/routes/wallet/dids.py
  app/services/onboarding/util/register_issuer_did.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/fixtures/credentials.py
  app/tests/util/regression_testing.py
  dockerfiles/agents/Dockerfile
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  endorser/services/endorsement_processor.py
  endorser/tests/test_endorser_processor.py
  endorser/util/endorsement.py
  shared/tests/__init__.py
  shared/tests/conftest.py
  shared/tests/test_rich_async_client.py
  shared/util/rich_async_client.py
Labels: bug, enhancement, tests

#1298 ⬇️ Python `~3.12.8`
  .github/workflows/sonarcloud.yml
  .github/workflows/style-check.yml
  .mise.toml
  .pylintrc
  README.md
  app/poetry.lock
  app/pyproject.toml
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1299 :heavy_minus_sign: Remove DDTrace
  app/poetry.lock
  app/pyproject.toml
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies

#1296 :art: Fix sonarcloud issues
  app/models/definitions.py
  app/routes/trust_registry.py
  app/services/issuer/acapy_issuer_v2.py
  app/services/trust_registry/actors.py
  app/services/trust_registry/schemas.py
  app/services/verifier/acapy_verifier_v2.py
  app/tests/e2e/issuer/test_indy_credentials.py
  app/tests/e2e/issuer/test_save_exchange_record.py
  app/tests/e2e/test_connections.py
  app/tests/e2e/test_jsonld.py
  app/tests/e2e/test_revocation.py
  app/tests/e2e/test_tenants.py
  app/tests/e2e/test_trust_registry.py
  app/tests/e2e/test_wallet_credentials.py
  app/tests/e2e/verifier/test_many_revocations.py
  app/tests/e2e/verifier/test_verifier.py
  app/tests/fixtures/credentials.py
  app/tests/routes/admin_tenants/test_get_tenants.py
  app/tests/routes/connections/test_create_invitation.py
  app/tests/routes/definitions/test_create_credential_definition.py
  app/tests/routes/definitions/test_get_credential_defifnition.py
  app/tests/routes/definitions/test_get_credential_definition_by_id.py
  app/tests/routes/definitions/test_get_schemas.py
  app/tests/routes/revocation/test_fix_revocation_registry.py
  app/tests/routes/wallet/dids/test_get_did_endpoint.py
  app/tests/routes/wallet/dids/test_set_did_endpoint.py
  app/tests/services/definitions/schema_publisher/test_schema_publisher.py
  app/tests/services/definitions/schemas/test_create_schemas.py
  app/tests/services/definitions/schemas/test_get_schemas_as_governance.py
  app/tests/services/definitions/schemas/test_get_schemas_by_id.py
  app/tests/services/test_acapy_wallet.py
  app/tests/services/test_revocation_registry.py
  app/tests/services/test_trust_registry.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  app/tests/services/verifier/test_verifier_utils.py
  app/tests/util/sse_listener.py
  app/tests/util/webhooks.py
  dockerfiles/agents/Dockerfile.agent
  dockerfiles/agents/Dockerfile.author.agent
  dockerfiles/endorser/Dockerfile
  dockerfiles/fastapi/Dockerfile
  dockerfiles/tests/Dockerfile
  dockerfiles/trustregistry/Dockerfile
  dockerfiles/waypoint/Dockerfile
  docs/src/Aries Cloud API Architecture.md
  docs/src/Example Flows.md
  docs/src/README.md
  endorser/tests/test_util_endorsement.py
  scripts/k6/Dockerfile
  shared/constants.py
  shared/models/endorsement.py
  trustregistry/migrations/env.py
  trustregistry/registry/registry_actors.py
  trustregistry/registry/registry_schemas.py
  trustregistry/tests/test_crud.py
Labels: improvement

#1293 ⚡️ Cache schema_Id calls from ledger
  app/poetry.lock
  app/pyproject.toml
  app/services/acapy_ledger.py
  app/tests/services/test_acapy_ledger.py
Labels: enhancement

#1308 :arrow_up: Upgrade lint dependencies: isort, black
  .github/workflows/style-check.yml
  .pre-commit-config.yaml
  app/poetry.lock
  app/pyproject.toml
  app/services/verifier/acapy_verifier_v2.py
  app/tests/services/event_handling/test_sse.py
  app/tests/services/verifier/test_acapy_verifier_v2.py
  endorser/poetry.lock
  endorser/pyproject.toml
  trustregistry/poetry.lock
  trustregistry/pyproject.toml
  waypoint/poetry.lock
  waypoint/pyproject.toml
Labels: dependencies
